### PR TITLE
Changes property header background and font color

### LINKED ISSUE #117: Change Color for Property Subheadings
In comments for https://github.com/LD4P/sinopia_profile_editor/issues/2#issuecomment-431191199, Michelle noted a bug with the Display of the Properties Subheadings, Astrid responded in comment https://github.com/LD4P/sinopia_profile_editor/issues/2#issuecomment-431200207 with a fix.

Creating this as separate issue to better track work.

### PR DESCRIPTION
**Pull request by jermnelson**
Fixes #117

### CODE REVIEW

**Comment by ndushay** [comment]
shouldn't this get a test?  Can you check for the colors?  Or is that simply too stupid to bother with?

**Comment by jgreben** [comment]
@jermnelson is it supposed to look like this?

**Comment by jermnelson** [comment]
Hi @jgreben,
I used the color hex code Astrid defined in her comment https://github.com/LD4P/sinopia_profile_editor/issues/2#issuecomment-431200207, I didn't change the display of Template for Property Section with a dotted line as it wasn't in the description.

**Comment by jgreben** [comment]
@jermnelson Seems like she wanted #F2E9D9 or 'Lighter Grey' for the property-panel, but maybe I'm misreading the comment thread. Maybe take a screenshot of the result for @astridu to review?

**Comment by astridu** [comment]
Sorry for the confusion. Michelle decided on the lighter gray, which is DFDFDF. Thank you!

**Pull request merged**
