### PR TITLE
Fetch Help and Resources menu content from github pages

### LINKED ISSUE #208: Help & Resources link on Profile Editor page needs to bring up same sidebar as Help & Resources on homepage and Editor page
the "Help & Resources" tab on the Profile Editor is not pointing to the latest Help & Resources content. If you compare the sidebar that comes up from sinopia.io or sinopia.io/editor to the one that comes up from profile-editor.sinopia.io you'll see the difference. 

sinopia.io and sinopia.io/editor Help & Resources link are bringing up the correct sidebar. can we just use the same sidebar on Profile Editor Help & Resources?

### PR DESCRIPTION
**Pull request by jgreben**
Fixes #208

### CODE REVIEW

**Comment by jgreben** [comment]
All the tests pass, but for some reason the tests are taking too long to exiting right now on circleci...merge anyway?  ¯\_(ツ)_/¯

**Comment by jermnelson** [comment]
I'm also getting a failing test when running locally but it is different from what failed on circle-ci. Doing investigating on my end.

**Comment by jgreben** [comment]
@jermnelson I re-ran it this morning and it looks like it passed this time. I think it was a problem with circleci. The tests also pass on my laptop. What is the failing test on your local system?

**Comment by ndushay** [comment]
with the discussion of yesterday fresh in our mind (and while trying to test my manual AWS deploy to dev and stage), I note there are no tests for this change.  Harumph.  Maybe make a ticket?

**Pull request merged**
